import time
from pywinauto.application import Application
import keyboard
app = Application().start("D:\Programs\PuTTY\putty.exe -ssh linuxoid@tty.sdf.org")
keyboard.write('Tn6CMjIoEyzng')
keyboard.send('enter')
time.sleep(1)
keyboard.send('enter')
time.sleep(1)
keyboard.send('enter')
time.sleep(1)
keyboard.send('enter')
time.sleep(1)
keyboard.send('enter')
time.sleep(1)
keyboard.send('enter')
time.sleep(1)
keyboard.send('enter')
time.sleep(10)
print("test")