# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWind(object):
    def setupUi(self, MainWind):
        MainWind.setObjectName("MainWind")
        MainWind.resize(600, 400)
        MainWind.setMinimumSize(QtCore.QSize(600, 400))
        MainWind.setMaximumSize(QtCore.QSize(600, 400))
        MainWind.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWind)
        self.centralwidget.setObjectName("centralwidget")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(10, 60, 581, 61))
        self.textEdit.setObjectName("textEdit")
        self.label_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_1.setGeometry(QtCore.QRect(10, 0, 581, 31))
        self.label_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_1.setObjectName("label_1")
        self.pushButton_1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_1.setGeometry(QtCore.QRect(10, 30, 581, 23))
        self.pushButton_1.setObjectName("pushButton_1")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 130, 581, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_x = QtWidgets.QLabel(self.centralwidget)
        self.label_x.setGeometry(QtCore.QRect(10, 190, 281, 141))
        self.label_x.setText("")
        self.label_x.setAlignment(QtCore.Qt.AlignCenter)
        self.label_x.setObjectName("label_x")
        self.label_y = QtWidgets.QLabel(self.centralwidget)
        self.label_y.setGeometry(QtCore.QRect(310, 190, 281, 141))
        self.label_y.setText("")
        self.label_y.setAlignment(QtCore.Qt.AlignCenter)
        self.label_y.setObjectName("label_y")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 160, 281, 21))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(310, 160, 281, 21))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 340, 581, 31))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(10, 370, 581, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        MainWind.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWind)
        QtCore.QMetaObject.connectSlotsByName(MainWind)

    def retranslateUi(self, MainWind):
        _translate = QtCore.QCoreApplication.translate
        MainWind.setWindowTitle(_translate("MainWind", "Code And Decode"))
        self.label_1.setText(_translate("MainWind", "Если вы хотите закодировать текст, то сначала выберите файл, а затем в поле ниже введите текст!"))
        self.pushButton_1.setText(_translate("MainWind", "Выбор изображения"))
        self.pushButton_2.setText(_translate("MainWind", "Зашифровать"))
        self.label_2.setText(_translate("MainWind", "Чистый"))
        self.label_3.setText(_translate("MainWind", "Шифрованный"))
        self.label_4.setText(_translate("MainWind", "Для расшифровки сначала выберите картинку выше, а затем нажмите на кнопку ниже!"))
        self.pushButton_3.setText(_translate("MainWind", "Расшифровать"))
